from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin/select_dashboard/', views.admin_select_dashboard, name='admin_select_dashboard'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('nurse_dashboard/', views.nurse_dashboard, name='nurse_dashboard'),
    path('nurse/', views.listar_enfermeros, name='enfermero_list'), 
    path('crear/', views.crear_enfermero, name='crear_enfermero'),
    path('editar/<str:pk>/', views.editar_enfermero, name='editar_enfermero'),
    path('eliminar/<str:pk>/', views.eliminar_enfermero, name='eliminar_enfermero'),
    path('patient/', views.listar_pacientes, name='listar_pacientes'),
    path('paciente/crear/', views.crear_paciente, name='crear_paciente'),
    path('paciente/<str:pk>/editar/', views.editar_paciente, name='editar_paciente'),
    path('paciente/<str:pk>/eliminar/', views.eliminar_paciente, name='eliminar_paciente'),
    path('medicamento/crear/', views.crear_medicamento, name='crear_medicamento'),
    path('medicamento/<pk>/editar/', views.editar_medicamento, name='editar_medicamento'),
    path('medicamento/<pk>/eliminar/', views.eliminar_medicamento, name='eliminar_medicamento'),
    path('medicine/', views.listar_medicamentos, name='listar_medicamentos'),
    path('horario/crear/', views.crear_horario, name='crear_horario'),
    path('schedule/', views.listar_horarios, name='listar_horarios'),
    path('horario/<pk>/editar/', views.editar_horario, name='editar_horario'),
    path('horario/<pk>/eliminar/', views.eliminar_horario, name='eliminar_horario'),
    path('administradores/', views.listar_administradores, name='listar_administradores'),
    path('administrador/crear/', views.crear_administrador, name='crear_administrador'),
    path('administrador/editar/<int:pk>/', views.editar_administrador, name='editar_administrador'),
    path('administrador/eliminar/<int:pk>/', views.eliminar_administrador, name='eliminar_administrador'),
    path('nurse/crear/', views.crear_enfermero, name='crear_enfermero'),
    path('nurse/editar/<int:pk>/', views.editar_enfermero, name='editar_enfermero'),
    path('nurse/', views.listar_enfermeros, name='listar_enfermeros'),
    path('nurse/eliminar/<int:pk>/', views.eliminar_enfermero, name='eliminar_enfermero'),
]
